name: log_box_in_app_webview_logger
description: "Log Box extension for in-app webview library"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.5.1
  flutter_inappwebview: ^6.1.0
  json_annotation: ^4.9.0

  log_box:
    git:
      url: https://github.com/robzimpulse/log_box.git
      ref: master
      path: packages/log_box

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^1.0.4
  flutter_inappwebview_platform_interface: ^1.3.0+1
  plugin_platform_interface: ^2.1.8
