enum WebviewEvent {
  onWebViewCreated,
  onContentSizeChanged,
  onLoadStart,
  onLoadStop,
  onProgressChanged,
  onReceivedError,
  onConsoleMessage,
  onRunJavascript,
  shouldOverrideUrlLoading,
  onTitleChanged,
  onLoadResource,
  shouldInterceptAjaxRequest,
  onAjaxProgress,
  onReceivedHttpError,
  onAjaxReadyStateChange,
}